customers_management/urls.py
from django.urls import path
from . import views

urlpatterns= [path('gestion_tipodocumento/', views.gestion_tipodocumento, name='gestion tipo documento'),
              path('gestion_tipodocumento/crear_tipo_documento/', views.crear_tipodocumento, name='crear tipo documento'),
              path('gestion_tipodocumento/modificar_tipo_documento/<int:idtipodocumento>/', views.modificar_tipodocumento, name='modificar tipo documento'),
              path('gestion_tipodocuemtno/eliminar_tipo_documento/<int:idtipodocumento>/', views.eliminar_tipo_documento, name='eliminar tipo documento'),
              path('gestion_tipo_cliente/', views.gestion_tipo_cliente, name='gestion tipo cliente'),
              path('gestion_tipo_cliente/crear_tipo_cliente/', views.crear_tipo_cliente, name='crear tipo cliente'),
              path('gestion_tipo_cliente/modificar_tipo_cliente/<int:idtipo_cliente>', views.modificar_tipo_cliente, name='modificar tipo cliente'),
              path('gestion_tipo_cliente/eliminar_tipo_cliente/<int:idtipo_cliente>/', views.eliminar_tipo_cliente, name='eliminar tipo cliente'),
              path('gestion_clientes/', views.gestion_clientes, name='gestion clientes'),
              path('gestion_clientes/crear_cliente/', views.crear_cliente, name='crear cliente'),
              path('gestion_clientes/modificar_cliente/<int:id_cliente>/', views.modificar_cliente, name='modificar cliente'),
              path('gestion_clientes/eliminar_cliente/<int:id_cliente>/', views.eliminar_cliente, name='eliminar cliente'),
              path('obtener_cliente/<int:id_tipo_documento>/<str:no_documento>/', views.obtener_cliente, name='obtener cliente'),


]

main/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns= [path('home/', views.homepage, name='homepage'),
              path('signin/', views.signin, name= 'signin'),
              # path('signin/', TemplateView.as_view(template_name= 'index.html'), name= 'signin'),
              path('signout/', views.signout, name= 'signout'),
              path('product_and_services/', include('product_services_management.urls')),
              path('users_management/', include('users_management.urls')),
              path('customers_management/', include('customers_management.urls')),
              path('sales_point/', include('sales_point.urls')),

]

sycowebproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('main.urls')),
    path('', include('users_management.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

customers_management/models.py
from django.db import models
from django.db.models import UniqueConstraint

# Create your models here.

class TipoDocumento(models.Model):
    nombre= models.CharField(max_length= 15)
    estado= models.BooleanField(default=True)
    creado= models.DateTimeField(auto_now_add=True)
    actualizado= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class TipoCliente(models.Model): # En desuso, marcado para ser eliminado en futuras versiones. Por ahora solo esta presente pero no tiene funcionalidad ni relacion con los demas modelos.
    nombre= models.CharField(max_length= 20)
    estado= models.BooleanField(default=True)
    creado= models.DateTimeField(auto_now_add=True)
    actualizado= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):

    TIPO_CLIENTE_CHOICES= [(1, 'Empresa'),
                           (2, 'Persona'),
                        ]

    tipo= models.IntegerField(choices= TIPO_CLIENTE_CHOICES, default=2)
    #tipo= models.ForeignKey(TipoCliente, on_delete= models.CASCADE, default=2) marcado para ser eliminada cuando se elimine el modelo TipoCliente.
    iddocumento= models.CharField(max_length=12)
    tipo_documento= models.ForeignKey(TipoDocumento, on_delete= models.CASCADE, default=1)
    razon_social= models.CharField(max_length=100, unique= True, null= True)
    nombre= models.CharField(max_length=25, null= True)
    apellido1= models.CharField(max_length= 15, null= True)
    apellido2= models.CharField(max_length= 15, null= True, blank= True)
    telefono= models.CharField(max_length=15, null= True, blank= True)
    direccion= models.CharField(max_length=100, null= True, blank= True)
    email= models.EmailField(max_length=30, null= True, blank= True)
    estado= models.BooleanField(default=True)
    creado= models.DateTimeField(auto_now_add=True)
    actualizado= models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.tipo == 1: # Empresa
            return self.razon_social
        else: # Persona
            return self.nombre+' '+self.apellido1+' '+self.apellido2

    class Meta:
        constraints = [UniqueConstraint(fields=['iddocumento', 'tipo_documento'], name='unique_document'),]

customers_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TipoDocumento, Cliente, TipoCliente
from .forms import FormCrearTipoDocumento, FormModificarTipoDocumento, FormCrearTipoCliente, FormModificarTipoCliente, FormCrearClienteEmpresa, FormCrearClientePersona, FormModificarClienteEmpresa, FormModificarClientePersona
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
# Create your views here.


@login_required
def gestion_tipodocumento(request):

    if request.method == 'GET':

        tipodocumento= Paginator(TipoDocumento.objects.all().order_by('id'), 10)

        if request.GET.get('page'):

            page_number= request.GET.get('page')

            tipodocumento_page= tipodocumento.get_page(page_number)
        
            return render(request, 'gestion_documentos.html',
            {'tipodocumentos': tipodocumento_page,
            'form':FormModificarTipoDocumento}
            )

        else:

            tipodocumento_page= tipodocumento.get_page(1)
        
            return render(request, 'gestion_documentos.html',
            {'tipodocumentos': tipodocumento_page,
            'form':FormModificarTipoDocumento}
            )

@login_required
def crear_tipodocumento(request):

    if request.method == 'GET':

        return render(request, 'formulario_crear_tipo_documento.html', {'form': FormCrearTipoDocumento})

    else:

        formcreartipodocumento = FormCrearTipoDocumento(request.POST)

        if formcreartipodocumento.is_valid():

            formcreartipodocumento.save()

            return redirect('gestion tipo documento')

        else:

            return render(request, 'formulario_crear_tipo_documento.html',
                        {'form': formcreartipodocumento,
                        'error':'Formulario invalido, no se ha podido crear el tipo de documento.'}
                        )

@login_required
def modificar_tipodocumento(request, idtipodocumento):

    if request.method == 'GET':

        tipodocumento= get_object_or_404(TipoDocumento, pk= idtipodocumento)

        formmodificartipodocumento= FormModificarTipoDocumento(instance=tipodocumento)

        return render(request, 'formulario_modificar_tipo_documento.html', {'form':formmodificartipodocumento})

    else:

        tipodocumento= get_object_or_404(TipoDocumento, pk= idtipodocumento)

        formmodificartipodocumento= FormModificarTipoDocumento(request.POST, instance=tipodocumento )

        if formmodificartipodocumento.is_valid():

            formmodificartipodocumento.save()

            return render(request, 'formulario_modificar_tipo_documento.html', 
                            {'form':formmodificartipodocumento,
                            'success':'El tipo de documento ha sido modificado.'}
                        )

        else:
            return render(request, 'formulario_modificar_tipo_documento.html',
                            {'form': formmodificartipodocumento,
                            'error':'Formulario invalido, no se ha podido realizar los cambios.'
                            }
                        )

@login_required
def eliminar_tipo_documento(request, idtipodocumento):

    if request.method == 'POST':

        tipodocumento= get_object_or_404(TipoDocumento, pk= idtipodocumento)
        tipodocumento.delete()
        return redirect('gestion tipo documento')

@login_required
def gestion_tipo_cliente(request):

    if request.method == 'GET':

        tipo_cliente= Paginator(TipoCliente.objects.all().order_by('id'), 10)

        if request.GET.get('page'):

            page_number= request.GET.get('page')

            tipo_cliente_page= tipo_cliente.get_page(page_number)
        
            return render(request, 'gestion_tipo_clientes.html',
                            {'tipoclientes': tipo_cliente_page,
                             'form': FormCrearTipoCliente}
                        )

        else:

            tipo_cliente_page= tipo_cliente.get_page(1)

            return render(request, 'gestion_tipo_clientes.html',
                            {'tipoclientes': tipo_cliente_page,
                             'form': FormCrearTipoCliente}
                        )

@login_required
def crear_tipo_cliente(request):

    if request.method == 'GET':

        return render(request, 'formulario_crear_tipo_cliente.html', {'form':FormCrearTipoCliente})

    else:

        formulario_tipo_cliente= FormCrearTipoCliente(request.POST)

        if formulario_tipo_cliente.is_valid():

            formulario_tipo_cliente.save()

            return redirect('gestion tipo cliente')

        else:

            return render(request, 'formulario_crear_tipo_cliente.html',                               {'form':formulario_tipo_cliente,
                'error':'Formularion invalido, no se ha podido crear tipo de cliente.'
            })

@login_required
def modificar_tipo_cliente(request, idtipo_cliente):

    if request.method == 'GET':

        tipo_cliente= get_object_or_404(TipoCliente, pk= idtipo_cliente)

        form_modificar_tipo_cliente= FormModificarTipoCliente(instance=tipo_cliente )

        return render(request, 'formulario_modificar_tipo_cliente.html', {'form':form_modificar_tipo_cliente})

    else:

        tipo_cliente= get_object_or_404(TipoCliente, pk= idtipo_cliente)

        form_modificar_tipo_cliente= FormModificarTipoCliente(request.POST, instance=tipo_cliente )

        if form_modificar_tipo_cliente.is_valid():

            form_modificar_tipo_cliente.save()

            return render(request, 'formulario_modificar_tipo_cliente.html', 
                            {'form':form_modificar_tipo_cliente,
                            'success':'El tipo de cliente ha sido modificado.'}
                        )

        else:

            return render(request, 'formulario_modificar_tipo_cliente.html',
                    {'form': form_modificar_tipo_cliente,
                    'error':'Formulario invalido, no se ha podido realizar los cambios.'
                    }
            )

@login_required
def eliminar_tipo_cliente(request, idtipo_cliente):

     if request.method == 'POST':

        tipo_cliente= get_object_or_404(TipoCliente, pk= idtipo_cliente)
        tipo_cliente.delete()
        return redirect('gestion tipo cliente')

@login_required
def gestion_clientes(request):

    if request.method == 'GET':

        cliente= Paginator(Cliente.objects.all().order_by('id'), 10)

        if request.GET.get('page'):

            page_number= request.GET.get('page')

            cliente_page= cliente.get_page(page_number)
        
            return render(request, 'gestion_clientes.html',
                            {'clientes': cliente_page,
                             'form': FormCrearClientePersona}
                        )

        else:

            cliente_page= cliente.get_page(1)

            return render(request, 'gestion_clientes.html',
                            {'clientes': cliente_page,
                             'form': FormCrearClientePersona}
                        )

@login_required
def crear_cliente(request):

    if request.method == 'GET':
        
        if request.GET.get('clientType'):

            tipo_de_cliente = int(request.GET.get('clientType'))

            if tipo_de_cliente == 2:
                return render(request, 'formulario_crear_cliente.html', {'form':FormCrearClientePersona})

            else:
                return render(request, 'formulario_crear_cliente.html', {'form':FormCrearClienteEmpresa(initial= {'tipo':1, 'tipo_documento':4})})

        else:
            return render(request, 'formulario_crear_cliente.html', {'form':FormCrearClientePersona(initial= {'tipo':2, 'tipo_documento':1})})

    else:
        try:
            tipo_de_cliente = int(request.POST.get('tipo'))

            if tipo_de_cliente == 1: # Es una Empresa.
                form_crear_cliente = FormCrearClienteEmpresa(request.POST)

                if form_crear_cliente.is_valid():
                    form_crear_cliente.save()
                    return redirect('gestion clientes')

                else: 
                    form_cliente = FormCrearClienteEmpresa(request.POST)
                    return render(request, 'formulario_crear_cliente.html',
                                {'form':form_cliente,
                                'error':'No se ha podido crear el cliente, error: %s.' %(form_cliente.errors.as_text())}
                                )

            else: # Es una Persona.

                form_crear_cliente = FormCrearClientePersona(request.POST)

                if form_crear_cliente.is_valid():
                    form_crear_cliente.save()
                    return redirect('gestion clientes')

                else: 
                    form_cliente = FormCrearClientePersona(request.POST)
                    return render(request, 'formulario_crear_cliente.html',
                                {'form':form_cliente,
                                'error':'No se ha podido crear el cliente, error: %s.' %(form_cliente.errors.as_text())}
                                )

        except Exception as error: 
        
            return render(request, 'formulario_crear_cliente.html',
                                  {'form':'',
                                  'error':'No se ha podido crear el cliente. error %s.' %(error)}
                        )

@login_required
def modificar_cliente(request, id_cliente):

    if request.method == 'GET':

        cliente = get_object_or_404(Cliente, pk= id_cliente)

        if cliente.tipo == 1: # Empresa

            form_modificar_cliente_empresa = FormModificarClienteEmpresa(instance= cliente)

            return render(request, 'formulario_modificar_cliente.html', {'form':form_modificar_cliente_empresa})

        else:

customers_management/templates/formulario_crear_cliente.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-8">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{error}}
    </div>
    {% elif success %}
    <div class="alert alert-success" role="alert">
        {{success}}
    </div>
    {% endif %}

    <form id="form_crear_cliente" method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
                <div class="{% if field.name == 'nombre' or field.name == 'direccion' or field.name == 'tipo'%} col-md-8 {% else %} col-md-5 {% endif %} mb-2">
                    <label for="{{ field.name }}" class="form-label fs-5">{{field.label}}</label>
                    {{field}}
                    <div class="invalid-feedback">
                    Por favor, llene este campo.
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar creación</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        ¿Esta seguro que desea crear este nuevo cliente?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="d-grid col-sm-8 gap-2 d-md-flex justify-content-md-start mt-3">
        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Guardar
        </button>
        <a class="btn btn-secondary" href="{% url 'gestion clientes' %}">Volver</a>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static '/js/script.js' %}"></script>

<script src="{% static '/js/validationscript.js' %}"></script>
{% endblock %}

customers_management/templates/formulario_crear_tipo_cliente.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
{% elif success %}
  <div class="alert alert-success" role="alert">
    {{success}}
  </div>
{% endif %}

<form method="post" class="needs-validation " novalidate>
    {% csrf_token %}

    {% for field in form %}
        <div class="mb-3 gy-2">
            <div class="col-sm-8 ">
                <label for="{{ field.name }}" class="form-label fs-5">{{field.label}}</label>
                {{field}}
                <div class="invalid-feedback">
                  Por favor, llene este campo.
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar creación</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ¿Esta seguro que desea crear este nuevo tipo de cliente?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-success">Guardar</button>
            </div>
          </div>
        </div>
      </div>
</form>
<br>
<div class="d-grid col-sm-8 gap-2 d-md-flex justify-content-md-end">
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Guardar
    </button>
    <a class="btn btn-secondary" href="{% url 'gestion tipo cliente' %}">Volver</a>
</div>

{% endblock %}
{% block script %}
<script src="{% static '/js/validationscript.js' %}"></script>
{% endblock %}

customers_management/templates/formulario_crear_tipo_documento.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
{% elif success %}
  <div class="alert alert-success" role="alert">
    {{success}}
  </div>
{% endif %}

<form method="post" class="needs-validation " novalidate>
    {% csrf_token %}

    {% for field in form %}
        <div class="mb-3 gy-2">
            <div class="col-sm-8 ">
                <label for="{{ field.name }}" class="form-label fs-5">{{field.label}}</label>
                {{field}}
                <div class="invalid-feedback">
                  Por favor, llene este campo.
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar creación</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ¿Esta seguro que desea crear este nuevo tipo de documento?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-success">Guardar</button>
            </div>
          </div>
        </div>
      </div>
</form>
<br>
<div class="d-grid col-sm-8 gap-2 d-md-flex justify-content-md-end">
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Guardar
    </button>
    <a class="btn btn-secondary" href="{% url 'gestion tipo documento' %}">Volver</a>
  </div>



{% endblock %}
{% block script %}
<script src="{% static '/js/validationscript.js' %}"></script>
{% endblock %}

customers_management/templates/formulario_modificar_tipo_cliente.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
{% elif success %}
  <div class="alert alert-success" role="alert">
    {{success}}
  </div>
{% endif %}

<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}

    {% for field in form %}
        <div class="mb-3 gy-2">
            <div class="col-sm-8 ">
                <label for="{{ field.name }}" class="form-label fs-5">{{field.label}}</label>
                {{field}}
                <div class="invalid-feedback">
                  Por favor, llene este campo.
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar cambios</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ¿Esta seguro que desea guardar los cambios?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-success">Guardar</button>
            </div>
          </div>
        </div>
      </div>
</form>
<br>
<div class="d-grid col-sm-8 gap-2 d-md-flex justify-content-md-end">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Modificar
    </button>
    <a class="btn btn-secondary" href="{% url 'gestion tipo cliente' %}">Volver</a>
</div>



{% endblock %}
{% block script %}
<script src="{% static '/js/validationscript.js' %}"></script>
{% endblock %}

customers_management/templates/formulario_modificar_tipo_documento.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
{% elif success %}
  <div class="alert alert-success" role="alert">
    {{success}}
  </div>
{% endif %}

<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}

    {% for field in form %}
        <div class="mb-3 gy-2">
            <div class="col-sm-8 ">
                <label for="{{ field.name }}" class="form-label fs-5">{{field.label}}</label>
                {{field}}
                <div class="invalid-feedback">
                  Por favor, llene este campo.
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar cambios</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ¿Esta seguro que desea guardar los cambios?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-success">Guardar</button>
            </div>
          </div>
        </div>
      </div>
</form>
<br>
<div class="d-grid col-sm-8 gap-2 d-md-flex justify-content-md-end">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Modificar
    </button>
    <a class="btn btn-secondary" href="{% url 'gestion tipo documento' %}">Volver</a>
</div>



{% endblock %}
{% block script %}
<script src="{% static '/js/validationscript.js' %}"></script>
{% endblock %}

customers_management/templates/gestion_clientes.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    
    <div class="row">
        <div class="col-md-3">
            <select class="form-select" id="inputGroupSelect01">
                {% for field in form %}
                <option value="{{field.label}}" selected>{{field.label}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-7">
            <div class="input-group mb-3 ">
                <input type="text" class="form-control" aria-label="Text input with dropdown button">
                <button class="btn btn-outline-secondary" type="button" id="button-addon1">Buscar</button>
            </div>
        </div>
        <div class="col-md-2">
            <a class="btn btn-primary" href="{% url 'crear cliente' %}">Nuevo Cliente</a>
        </div>
    </div>
    <br>
    <table class="table table-hover align-middle">
        <thead class="text-white" style="background-color: #0E4749;">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Documento</th>
                <th scope="col">No. Documento</th>
                <th scope="col">Tipo</th>
                <th scope="col">Estado</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr>
                <th scope="row">{{cliente.id}}</th>
                <td>{% if cliente.tipo == 2 %} {{cliente.nombre}} {{cliente.apellido1}} {{cliente.apellido2}} {% else %} {{cliente.razon_social}} {% endif %}</td>
                <td>{{cliente.tipo_documento}}</td>
                <td>{{cliente.iddocumento}}</td>
                <td>{{cliente.get_tipo_display}}</td>
                <td>{% if cliente.estado %}Activo{% else %}Inactivo{% endif %}</td>
                <td>
                    <a class="btn btn-sm btn-warning" href="{% url 'modificar cliente' cliente.id %}" role="button">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" style="fill:#FFF"><path d="M5 19h1.4l8.625-8.625-1.4-1.4L5 17.6ZM19.3 8.925l-4.25-4.2 1.4-1.4q.575-.575 1.413-.575.837 0 1.412.575l1.4 1.4q.575.575.6 1.388.025.812-.55 1.387ZM17.85 10.4 7.25 21H3v-4.25l10.6-10.6Zm-3.525-.725-.7-.7 1.4 1.4Z"/></svg>
                    </a>
                    <button class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModalgestion" data-bs-whatever="{{cliente.id}}:{% if cliente.tipo == 2 %}{{cliente.nombre}} {{cliente.apellido1}} {{cliente.apellido2}}{% else %}{{cliente.razon_social}}{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" style="fill:#FFF"><path d="M7 21q-.825 0-1.412-.587Q5 19.825 5 19V6H4V4h5V3h6v1h5v2h-1v13q0 .825-.587 1.413Q17.825 21 17 21ZM17 6H7v13h10ZM9 17h2V8H9Zm4 0h2V8h-2ZM7 6v13Z"/></svg>
                    </button>
                </td>
            {% empty %}
                <th scope="row" colspan="7" class="text-center"> No hay cliente</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
        
            <li class="page-item {% if not clientes.has_previous %} disabled {% endif %}">
                <a class="page-link" {% if clientes.has_previous %} href="?page={{ clientes.previous_page_number }}" {% endif %}>Previous</a>
            </li>
            
            {% for i in clientes.paginator.page_range %}
  
              {% if i == clientes.number %}
                  <li class="page-item active">
                      <a class="page-link" href="#">{{ i }}</a>
                  </li>
              {% else %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                  </li>
              {% endif %}
              
          {% endfor %}
          
          <li class="page-item {% if not clientes.has_next %} disabled {% endif %}" >
            <a class="page-link" {% if clientes.has_next %} href="?page={{ clientes.next_page_number }}" {% endif %}>Next</a>
          </li>
        </ul>
    </nav>

    <div class="modal fade" id="exampleModalgestion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar Cliente</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              
              
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Volver</button>
                <form action="{% url 'eliminar cliente' 0 %}" method="post" id="form_eliminar">
                    {% csrf_token %}
                    <button class="btn btn-danger">Eliminar</button>
                </form>
            </div>
          </div>
        </div>
    </div>
    
{% endblock %}
{% block script %}
    <script src="{% static '/js/script_gestionModal.js' %}"></script>
{% endblock %}